import React, { useState } from 'react';
import { 
  ArrowLeft,
  ChevronRight,
  Upload, 
  FolderUp, 
  FileText, 
  CheckCircle2, 
  ExternalLink, 
  Folder, 
  AlertCircle, 
  Sparkles, 
  Copy, 
  Check,
  Link as LinkIcon,
  Send,
  Lock
} from 'lucide-react';
import { ExamItem, TeacherUser } from '../types/exam';

export interface ExamUploadDrivePageProps {
  exam: ExamItem;
  currentUser: TeacherUser | null;
  centralDriveFolderUrl: string;
  webhookUrl?: string;
  onBack: () => void;
  onUploadSuccess: (examId: string, fileUrl: string, uploadedDate: string) => void;
}

export const ExamUploadDrivePage: React.FC<ExamUploadDrivePageProps> = ({
  exam,
  currentUser,
  centralDriveFolderUrl,
  webhookUrl,
  onBack,
  onUploadSuccess
}) => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [customDriveLink, setCustomDriveLink] = useState<string>(exam.examLink || '');
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState<string>('');
  const [uploadSuccessResult, setUploadSuccessResult] = useState<{
    fileUrl: string;
    folderUrl?: string;
    fileName: string;
  } | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copiedName, setCopiedName] = useState(false);

  const isAlreadySubmitted = exam.examSubmissionStatus === 'submitted';
  const isAdmin = currentUser?.role === 'admin';
  const isLocked = isAlreadySubmitted && !isAdmin;

  const teacherName = (currentUser?.name || exam.lecturer || 'อาจารย์ผู้สอน').trim();
  const fileExtension = selectedFile 
    ? (selectedFile.name.includes('.') ? selectedFile.name.substring(selectedFile.name.lastIndexOf('.')) : '.pdf')
    : '.pdf';
  
  const studentStatus = exam.status || 'บรรพชิต';
  const targetFolderName = `ชั้นปีที่ ${exam.yearLevel} (${studentStatus})`;
  
  // Standard Auto-generated File Name: [ปี X][บรรพชิต/คฤหัสถ์][สาขาวิชา][รหัสวิชา] ชื่อวิชา - ชื่ออาจารย์.ext
  const autoGeneratedFileName = `[ปี ${exam.yearLevel}][${studentStatus}][${exam.major || exam.faculty}][${exam.courseCode}] ${exam.courseName} - ${teacherName}${fileExtension}`;

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setSelectedFile(file);
      setErrorMessage(null);
    }
  };

  const handleCopyStandardName = () => {
    navigator.clipboard.writeText(autoGeneratedFileName);
    setCopiedName(true);
    setTimeout(() => setCopiedName(false), 2000);
  };

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const result = reader.result as string;
        const base64 = result.split(',')[1];
        resolve(base64);
      };
      reader.onerror = (error) => reject(error);
    });
  };

  const handleUploadToDriveWithWebhook = async () => {
    if (!selectedFile) {
      setErrorMessage('กรุณาเลือกไฟล์ข้อสอบ (PDF หรือ Word) ก่อนกดส่ง');
      return;
    }

    if (!webhookUrl) {
      setErrorMessage('ไม่พบ Google Apps Script Webhook URL ในการตั้งค่า กรุณาใช้ตัวเลือกการส่งแบบบันทึกประวัติด้านล่าง');
      return;
    }

    try {
      setIsUploading(true);
      setErrorMessage(null);
      setUploadProgress('กำลังเข้ารหัสและเตรียมส่งไฟล์ข้อสอบ...');

      const base64Content = await fileToBase64(selectedFile);

      setUploadProgress('กำลังส่งไฟล์ขึ้น Google Drive อัตโนมัติ...');

      let folderId = '1yc7VLWVCYtH8n1NqWymKmeu1kaNJRDBa';
      const match = centralDriveFolderUrl.match(/folders\/([a-zA-Z0-9_-]+)/);
      if (match && match[1]) {
        folderId = match[1];
      }

      const payload = {
        action: 'upload_exam',
        folderId: folderId,
        courseCode: exam.courseCode,
        courseName: exam.courseName,
        yearLevel: exam.yearLevel,
        studentStatus: exam.status || 'บรรพชิต',
        status: exam.status || 'บรรพชิต',
        faculty: exam.faculty,
        major: exam.major || '',
        teacherName: teacherName,
        lecturer: teacherName,
        examDateThai: exam.examDateThai,
        examTimeThai: exam.examTimeThai,
        fileName: autoGeneratedFileName,
        fileMime: selectedFile.type || 'application/pdf',
        mimeType: selectedFile.type || 'application/pdf',
        fileData: base64Content,
        fileContent: base64Content
      };

      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'text/plain;charset=utf-8'
        },
        body: JSON.stringify(payload)
      });

      const result = await response.json();

      if (result.status === 'success' || result.success || result.fileUrl) {
        const now = new Date();
        const thaiDate = now.toLocaleDateString('th-TH', { 
          day: 'numeric', 
          month: 'short', 
          year: '2-digit' 
        });
        const thaiTime = now.toLocaleTimeString('th-TH', { 
          hour: '2-digit', 
          minute: '2-digit' 
        });
        const uploadDateStr = `${thaiDate} ${thaiTime} น.`;

        setUploadSuccessResult({
          fileUrl: result.fileUrl || centralDriveFolderUrl,
          folderUrl: result.folderUrl || centralDriveFolderUrl,
          fileName: autoGeneratedFileName
        });

        onUploadSuccess(exam.id, result.fileUrl || centralDriveFolderUrl, uploadDateStr);
      } else {
        throw new Error(result.message || 'ส่งไฟล์ไม่สำเร็จ กรุณาลองใหม่อีกครั้ง');
      }
    } catch (err: any) {
      console.error('Upload Error:', err);
      setErrorMessage(`เกิดข้อผิดพลาด: ${err.message || 'ไม่สามารถเชื่อมต่อ Google Drive Webhook ได้'}`);
    } finally {
      setIsUploading(false);
      setUploadProgress('');
    }
  };

  const handleManualMarkSubmitted = () => {
    const now = new Date();
    const thaiDate = now.toLocaleDateString('th-TH', { 
      day: 'numeric', 
      month: 'short', 
      year: '2-digit' 
    });
    const thaiTime = now.toLocaleTimeString('th-TH', { 
      hour: '2-digit', 
      minute: '2-digit' 
    });
    const uploadDateStr = `${thaiDate} ${thaiTime} น.`;

    const finalLink = customDriveLink.trim() || centralDriveFolderUrl;

    onUploadSuccess(exam.id, finalLink, uploadDateStr);

    setUploadSuccessResult({
      fileUrl: finalLink,
      folderUrl: centralDriveFolderUrl,
      fileName: selectedFile ? selectedFile.name : autoGeneratedFileName
    });
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* 1. Navigation Breadcrumb Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-white/90 backdrop-blur-sm p-4 rounded-2xl border border-[#F8D7E3] shadow-xs">
        <div className="flex items-center gap-3">
          <button
            onClick={onBack}
            className="inline-flex items-center gap-2 px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-[#FFF0F5] text-slate-700 hover:text-[#9D174D] border border-slate-200 hover:border-[#F8D7E3] font-medium text-sm transition cursor-pointer shadow-xs"
          >
            <ArrowLeft className="w-4 h-4 text-[#9D174D]" />
            <span>ย้อนกลับ</span>
          </button>
          <div className="flex items-center gap-2 text-xs sm:text-sm text-slate-500">
            <button onClick={onBack} className="hover:text-[#9D174D] transition cursor-pointer">หน้าหลัก</button>
            <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
            <span className="cursor-pointer hover:text-[#9D174D]" onClick={onBack}>รายละเอียดรายวิชา</span>
            <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
            <span className="font-semibold text-[#9D174D]">ส่งข้อสอบ Google Drive ({exam.courseCode})</span>
          </div>
        </div>
      </div>

      {/* 2. Main Upload Card */}
      <div className="bg-white rounded-3xl border border-[#F8D7E3] shadow-sm overflow-hidden">
        {/* Banner Header */}
        <div className="bg-gradient-to-r from-[#FFF0F5] via-[#FFF5F8] to-[#FFF0F5] border-b border-[#F8D7E3] p-6 sm:p-8">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-2xl bg-[#9D174D] text-white flex items-center justify-center shrink-0 shadow-xs">
              <FolderUp className="w-6 h-6 text-rose-100" />
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-2 mb-1.5">
                <span className="px-2.5 py-0.5 rounded-lg text-xs font-bold bg-[#9D174D] text-white">
                  {exam.courseCode}
                </span>
                <span className="px-2.5 py-0.5 rounded-lg text-xs font-semibold bg-pink-100 text-[#9D174D]">
                  {exam.status} (ปี {exam.yearLevel})
                </span>
              </div>
              <h1 className="text-xl sm:text-2xl font-bold text-slate-900">
                ส่งข้อสอบปลายภาคเข้าสู่ Google Drive
              </h1>
              <p className="text-xs sm:text-sm text-slate-600 mt-1">
                วิชา: {exam.courseName} | อาจารย์: {teacherName}
              </p>
            </div>
          </div>
        </div>

        {/* 3. Form Content */}
        <div className="p-6 sm:p-8 space-y-6">
          {/* Locked Notification if already submitted and not Admin */}
          {isLocked && (
            <div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 flex items-start gap-3">
              <Lock className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
              <div className="text-xs sm:text-sm space-y-1">
                <div className="font-bold">รายวิชานี้ส่งข้อสอบเรียบร้อยแล้ว (สถานะ: พร้อมสอบ ✔)</div>
                <div className="text-slate-600">
                  ระบบตั้งเงื่อนไขห้ามอัปโหลดหรือแก้ไขซ้ำ เพื่อป้องกันความซ้ำซ้อน หากต้องการปรับปรุงข้อสอบ กรุณาติดต่อผู้ดูแลระบบ (Admin)
                </div>
              </div>
            </div>
          )}

          {/* Success Box */}
          {uploadSuccessResult && (
            <div className="p-5 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-900 space-y-3">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-full bg-emerald-100 flex items-center justify-center text-emerald-700 shrink-0">
                  <CheckCircle2 className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="font-bold text-sm sm:text-base text-emerald-950">ส่งข้อสอบสำเร็จเรียบร้อยแล้ว!</h4>
                  <p className="text-xs text-emerald-800">ระบบบันทึกสถานะเป็น [พร้อมสอบ] เรียบร้อย</p>
                </div>
              </div>
              <div className="bg-white/80 p-3 rounded-xl border border-emerald-200/60 text-xs font-mono text-slate-700 truncate">
                📄 {uploadSuccessResult.fileName}
              </div>
              <div className="flex flex-wrap gap-2 pt-1">
                <a
                  href={uploadSuccessResult.fileUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-emerald-700 hover:bg-emerald-800 text-white font-bold text-xs transition shadow-xs"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>เปิดดูไฟล์ข้อสอบใน Google Drive</span>
                </a>
                <button
                  onClick={onBack}
                  className="inline-flex items-center gap-1 px-3 py-1.5 rounded-xl bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 text-xs font-medium transition"
                >
                  <span>กลับหน้ารายละเอียดรายวิชา</span>
                </button>
              </div>
            </div>
          )}

          {/* Target Folder Hierarchy Preview */}
          <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-2">
            <div className="flex items-center gap-2 text-xs font-bold text-slate-700">
              <Folder className="w-4 h-4 text-amber-500" />
              <span>ตำแหน่งโฟลเดอร์จัดเก็บข้อสอบปลายทางใน Google Drive:</span>
            </div>
            <div className="flex flex-wrap items-center gap-1.5 text-xs text-slate-600 font-mono bg-white p-2.5 rounded-xl border border-slate-200/80">
              <span className="font-semibold text-slate-800">📁 Google Drive กลาง</span>
              <span>&gt;</span>
              <span className="px-2 py-0.5 rounded bg-pink-50 text-[#9D174D] font-bold">
                ภาค{exam.status}
              </span>
              <span>&gt;</span>
              <span className="px-2 py-0.5 rounded bg-blue-50 text-blue-700 font-bold">
                {targetFolderName}
              </span>
              <span>&gt;</span>
              <span className="px-2 py-0.5 rounded bg-amber-50 text-amber-800 font-bold">
                {exam.faculty}
              </span>
            </div>
          </div>

          {/* Standard Auto-naming Box */}
          <div className="p-4 rounded-2xl bg-[#FFF0F5]/50 border border-[#F8D7E3] space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs font-bold text-[#701A4B]">
                <Sparkles className="w-4 h-4 text-[#9D174D]" />
                <span>รูปแบบชื่อไฟล์ข้อสอบมาตรฐาน (ระบบสร้างให้อัตโนมัติ):</span>
              </div>
              <button
                onClick={handleCopyStandardName}
                className="inline-flex items-center gap-1 text-[11px] font-bold text-[#9D174D] hover:underline cursor-pointer"
              >
                {copiedName ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    <span className="text-emerald-700">คัดลอกชื่อแล้ว!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>คัดลอกชื่อไฟล์</span>
                  </>
                )}
              </button>
            </div>
            <div className="text-xs font-mono text-slate-800 bg-white p-2.5 rounded-xl border border-[#F8D7E3] break-all">
              {autoGeneratedFileName}
            </div>
          </div>

          {/* File Picker & Upload Area */}
          <div className="space-y-4">
            <label className="block text-xs font-bold text-slate-700">
              เลือกไฟล์ต้นฉบับข้อสอบ (PDF หรือ Word):
            </label>
            <div className="border-2 border-dashed border-slate-300 hover:border-[#9D174D] rounded-3xl p-6 sm:p-8 text-center transition bg-slate-50/50 hover:bg-[#FFF0F5]/20">
              <input
                type="file"
                id="exam-file-input"
                accept=".pdf,.doc,.docx"
                onChange={handleFileChange}
                disabled={isLocked || isUploading}
                className="hidden"
              />
              <label
                htmlFor="exam-file-input"
                className={`cursor-pointer flex flex-col items-center justify-center gap-2 ${
                  isLocked ? 'cursor-not-allowed opacity-50' : ''
                }`}
              >
                <div className="w-14 h-14 rounded-2xl bg-[#FFF0F5] text-[#9D174D] flex items-center justify-center shadow-xs">
                  <Upload className="w-7 h-7" />
                </div>
                {selectedFile ? (
                  <div className="space-y-1">
                    <div className="font-bold text-sm text-slate-900 flex items-center justify-center gap-1.5">
                      <FileText className="w-4 h-4 text-[#9D174D]" />
                      <span>{selectedFile.name}</span>
                    </div>
                    <div className="text-xs text-slate-500">
                      ขนาด: {(selectedFile.size / (1024 * 1024)).toFixed(2)} MB (คลิกเพื่อเปลี่ยนไฟล์)
                    </div>
                  </div>
                ) : (
                  <div className="space-y-1">
                    <div className="font-bold text-sm text-slate-800">
                      คลิกเพื่อเลือกไฟล์ข้อสอบ หรือลากไฟล์มาวางที่นี่
                    </div>
                    <div className="text-xs text-slate-500">
                      รองรับไฟล์ .PDF, .DOC, .DOCX ขนาดไม่เกิน 50 MB
                    </div>
                  </div>
                )}
              </label>
            </div>
          </div>

          {/* Error Message */}
          {errorMessage && (
            <div className="p-3.5 rounded-xl bg-rose-50 border border-rose-200 text-rose-800 text-xs flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0" />
              <span>{errorMessage}</span>
            </div>
          )}

          {/* Action Submission Buttons */}
          <div className="pt-4 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-3">
            <button
              onClick={onBack}
              className="w-full sm:w-auto px-5 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs sm:text-sm transition cursor-pointer"
            >
              ยกเลิกและย้อนกลับ
            </button>

            <div className="flex flex-col sm:flex-row items-center gap-2 w-full sm:w-auto">
              {/* Option A: Webhook Upload */}
              {webhookUrl && (
                <button
                  onClick={handleUploadToDriveWithWebhook}
                  disabled={isLocked || isUploading || !selectedFile}
                  className={`w-full sm:w-auto inline-flex items-center justify-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-[#9D174D] to-[#701A4B] text-white font-bold text-xs sm:text-sm shadow-md transition cursor-pointer ${
                    isLocked || isUploading || !selectedFile ? 'opacity-50 cursor-not-allowed' : 'hover:opacity-95'
                  }`}
                >
                  <Send className="w-4 h-4" />
                  <span>{isUploading ? (uploadProgress || 'กำลังส่ง...') : 'ส่งข้อสอบอัตโนมัติ (Drive Webhook)'}</span>
                </button>
              )}

              {/* Option B: Standard Record Submission */}
              <button
                onClick={handleManualMarkSubmitted}
                disabled={isLocked || isUploading}
                className={`w-full sm:w-auto inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs sm:text-sm shadow-md transition cursor-pointer ${
                  isLocked || isUploading ? 'opacity-50 cursor-not-allowed' : ''
                }`}
              >
                <CheckCircle2 className="w-4 h-4" />
                <span>ยืนยันการส่งข้อสอบและบันทึกสถานะ</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
