import React, { useState } from 'react';
import { 
  X, 
  Upload, 
  FolderUp, 
  FileText, 
  CheckCircle2, 
  ExternalLink, 
  Folder, 
  AlertCircle, 
  Sparkles, 
  Copy, 
  Check,
  Link as LinkIcon,
  Send,
  Lock
} from 'lucide-react';
import { ExamItem, TeacherUser } from '../types/exam';

interface ExamUploadDriveModalProps {
  isOpen: boolean;
  onClose: () => void;
  exam: ExamItem | null;
  currentUser: TeacherUser | null;
  centralDriveFolderUrl: string;
  webhookUrl?: string;
  onUploadSuccess: (examId: string, fileUrl: string, uploadedDate: string) => void;
}

export const ExamUploadDriveModal: React.FC<ExamUploadDriveModalProps> = ({
  isOpen,
  onClose,
  exam,
  currentUser,
  centralDriveFolderUrl,
  webhookUrl,
  onUploadSuccess
}) => {
  if (!isOpen || !exam) return null;

  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [customDriveLink, setCustomDriveLink] = useState<string>(exam.examLink || '');
  const [isUploading, setIsUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState<string>('');
  const [uploadSuccessResult, setUploadSuccessResult] = useState<{
    fileUrl: string;
    folderUrl?: string;
    fileName: string;
  } | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copiedName, setCopiedName] = useState(false);

  const isAlreadySubmitted = exam.examSubmissionStatus === 'submitted';
  const isAdmin = currentUser?.role === 'admin';
  const isLocked = isAlreadySubmitted && !isAdmin;

  const teacherName = (currentUser?.name || exam.lecturer || 'อาจารย์ผู้สอน').trim();
  const fileExtension = selectedFile 
    ? (selectedFile.name.includes('.') ? selectedFile.name.substring(selectedFile.name.lastIndexOf('.')) : '.pdf')
    : '.pdf';
  
  const studentStatus = exam.status || 'บรรพชิต';
  const targetFolderName = `ชั้นปีที่ ${exam.yearLevel} (${studentStatus})`;
  
  // Standard Auto-generated File Name: [ปี X][บรรพชิต/คฤหัสถ์][สาขาวิชา][รหัสวิชา] ชื่อวิชา - ชื่ออาจารย์.ext
  const autoGeneratedFileName = `[ปี ${exam.yearLevel}][${studentStatus}][${exam.major || exam.faculty}][${exam.courseCode}] ${exam.courseName} - ${teacherName}${fileExtension}`;

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setSelectedFile(file);
      setErrorMessage(null);
    }
  };

  const handleCopyStandardName = () => {
    navigator.clipboard.writeText(autoGeneratedFileName);
    setCopiedName(true);
    setTimeout(() => setCopiedName(false), 2000);
  };

  // Convert File to Base64
  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const result = reader.result as string;
        const base64 = result.split(',')[1];
        resolve(base64);
      };
      reader.onerror = (error) => reject(error);
    });
  };

  // 1. Submit via Apps Script Webhook (Automated direct upload)
  const handleUploadToDriveWithWebhook = async () => {
    if (!selectedFile) {
      setErrorMessage('กรุณาเลือกไฟล์ข้อสอบ (PDF หรือ Word) ก่อนกดส่ง');
      return;
    }

    setIsUploading(true);
    setErrorMessage(null);
    setUploadProgress('กำลังเตรียมไฟล์และแปลงข้อมูล...');

    try {
      const base64Data = await fileToBase64(selectedFile);
      setUploadProgress('กำลังส่งไฟล์และสร้างโฟลเดอร์ชื่ออาจารย์บน Google Drive...');

      let folderId = '1yc7VLWVCYtH8n1NqWymKmeu1kaNJRDBa';
      const match = centralDriveFolderUrl.match(/folders\/([a-zA-Z0-9_-]+)/);
      if (match && match[1]) {
        folderId = match[1];
      }

      const payload = {
        action: 'upload_exam',
        folderId: folderId,
        yearLevel: exam.yearLevel,
        studentStatus: studentStatus,
        major: exam.major,
        faculty: exam.faculty,
        teacherName: teacherName,
        courseCode: exam.courseCode,
        courseName: exam.courseName,
        fileName: autoGeneratedFileName,
        fileMime: selectedFile.type || 'application/pdf',
        fileData: base64Data
      };

      const res = await fetch(webhookUrl!, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain;charset=utf-8' },
        body: JSON.stringify(payload)
      });

      const data = await res.json();

      if (data.status === 'success' || data.fileUrl) {
        const now = new Date();
        const dateStr = now.toLocaleDateString('th-TH', { 
          day: 'numeric', 
          month: 'short', 
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        }) + ' น.';

        const finalUrl = data.fileUrl || customDriveLink.trim() || centralDriveFolderUrl;

        setUploadSuccessResult({
          fileUrl: finalUrl,
          folderUrl: data.folderUrl || centralDriveFolderUrl,
          fileName: data.fileName || autoGeneratedFileName
        });

        onUploadSuccess(exam.id, finalUrl, dateStr);
      } else {
        throw new Error(data.message || 'Apps Script ตอบกลับด้วยสถานะไม่สำเร็จ');
      }
    } catch (err) {
      // Fallback: If webhook network fails, still give instructor option to confirm
      setErrorMessage(`เกิดข้อผิดพลาดในการเชื่อมต่อ Webhook: ${(err as Error).message} (ท่านสามารถกดปุ่ม "ยืนยันการส่งข้อสอบ" ด้านล่างเพื่อบันทึกสถานะได้ทันที)`);
    } finally {
      setIsUploading(false);
      setUploadProgress('');
    }
  };

  // 2. Direct Confirmation (Works always, with or without webhook)
  const handleConfirmSubmission = () => {
    if (isLocked) {
      setErrorMessage('รายวิชานี้ส่งข้อสอบแล้ว ไม่อนุญาตให้อัปโหลดซ้ำ เพื่อป้องกันความซ้ำซ้อน');
      return;
    }

    setIsUploading(true);
    setErrorMessage(null);

    try {
      const now = new Date();
      const dateStr = now.toLocaleDateString('th-TH', { 
        day: 'numeric', 
        month: 'short', 
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      }) + ' น.';

      const targetUrl = customDriveLink.trim() || centralDriveFolderUrl || exam.driveFolderUrl || exam.examLink || '';

      setUploadSuccessResult({
        fileUrl: targetUrl,
        fileName: selectedFile ? selectedFile.name : autoGeneratedFileName
      });

      onUploadSuccess(exam.id, targetUrl, dateStr);
    } catch (err) {
      setErrorMessage(`เกิดข้อผิดพลาด: ${(err as Error).message}`);
    } finally {
      setIsUploading(false);
    }
  };

  // Unified submit handler called by the primary "ส่งข้อสอบ" button
  const handlePrimarySubmit = () => {
    if (isLocked) {
      setErrorMessage('รายวิชานี้ส่งข้อสอบแล้ว ไม่อนุญาตให้อัปโหลดซ้ำ เพื่อป้องกันความซ้ำซ้อน');
      return;
    }

    if (webhookUrl && selectedFile) {
      handleUploadToDriveWithWebhook();
    } else {
      handleConfirmSubmission();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/60 backdrop-blur-xs animate-in fade-in duration-200 overflow-y-auto">
      <div className="bg-white rounded-3xl shadow-2xl max-w-lg w-full border border-emerald-200 overflow-hidden my-6">
        {/* Header */}
        <div className="bg-gradient-to-r from-emerald-50 via-emerald-100/70 to-emerald-50 text-emerald-950 p-4 sm:p-5 flex items-center justify-between border-b border-emerald-200">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-white border border-emerald-300 text-emerald-700 flex items-center justify-center shadow-2xs">
              <FolderUp className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base leading-tight">
                ส่งข้อสอบเข้า Google Drive
              </h3>
              <p className="text-xs text-emerald-800/80 mt-0.5">
                อัปโหลดไฟล์หรือบันทึกสถานะการส่งข้อสอบของรายวิชา
              </p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-1.5 text-emerald-800 hover:bg-emerald-200/60 rounded-xl transition cursor-pointer"
            title="ปิดหน้าต่าง"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-4 sm:p-5 space-y-4">
          {/* Target Course Details */}
          <div className="p-3.5 bg-[#FFF8FA] rounded-2xl border border-[#F8D7E3] space-y-1.5">
            <div className="flex items-center justify-between">
              <span className="font-mono font-bold text-xs px-2 py-0.5 rounded bg-white text-[#701A4B] border border-[#F8D7E3]">
                {exam.courseCode}
              </span>
              <span className="text-xs text-[#854D67]">
                {exam.faculty} · ปี {exam.yearLevel}
              </span>
            </div>
            <h4 className="font-bold text-sm text-slate-900 leading-snug">
              {exam.courseName}
            </h4>
            <p className="text-xs text-slate-600 flex items-center gap-1">
              <span>อาจารย์ผู้บรรยาย:</span>
              <span className="font-semibold text-[#701A4B]">{teacherName}</span>
            </p>
          </div>

          {/* Automatic Folder & File Naming Info */}
          <div className="p-3 bg-emerald-50/70 rounded-2xl border border-emerald-200 text-xs space-y-2">
            <div className="flex items-start gap-2">
              <Folder className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <span className="text-slate-600 text-[11px] block">Google Drive จะบันทึกในโฟลเดอร์แยกตามชั้นปีและกลุ่ม (รูปแบบ ข):</span>
                <span className="font-bold text-emerald-950 font-mono text-xs">
                  📁 {targetFolderName}
                </span>
                <span className="text-[10px] text-emerald-700 block mt-0.5">
                  (สร้างและจัดเก็บอัตโนมัติภายใน Google Drive กลางของวิทยาลัย)
                </span>
              </div>
            </div>

            <div className="flex items-start gap-2 pt-1 border-t border-emerald-200/60">
              <FileText className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div className="flex-1">
                <span className="text-slate-600 text-[11px] block">ชื่อไฟล์มาตรฐานของวิชานี้:</span>
                <div className="flex items-center justify-between gap-1 bg-white px-2 py-1 rounded-lg border border-emerald-200 mt-0.5">
                  <span className="font-mono text-[11px] text-slate-800 font-semibold truncate">
                    {autoGeneratedFileName}
                  </span>
                  <button
                    type="button"
                    onClick={handleCopyStandardName}
                    className="text-emerald-700 hover:text-emerald-900 p-0.5 shrink-0 cursor-pointer"
                    title="คัดลอกชื่อไฟล์มาตรฐานนี้"
                  >
                    {copiedName ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Upload Success State */}
          {uploadSuccessResult ? (
            <div className="p-5 bg-emerald-50 border-2 border-emerald-400 rounded-2xl text-center space-y-3.5 animate-in zoom-in-95 duration-200">
              <div className="w-12 h-12 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mx-auto">
                <CheckCircle2 className="w-8 h-8" />
              </div>
              <div>
                <h4 className="font-bold text-base text-emerald-950">
                  {webhookUrl ? 'ส่งไฟล์เข้า Google Drive สำเร็จเรียบร้อย!' : 'บันทึกสถานะ "พร้อมสอบ ✔" เรียบร้อย!'}
                </h4>
                <p className="text-xs text-emerald-800 mt-1">
                  ระบบได้บันทึกสถานะ <span className="font-bold text-emerald-900">"พร้อมสอบ ✔"</span> ให้กับวิชา {exam.courseName}
                </p>
                <p className="text-[11px] text-emerald-700 mt-0.5 font-mono">
                  {uploadSuccessResult.fileName}
                </p>
                {!webhookUrl && (
                  <div className="mt-3 p-3 bg-white/90 rounded-xl border border-emerald-300 text-left text-xs text-slate-700 space-y-1">
                    <span className="font-bold text-emerald-950 block">📌 การนำไฟล์เข้า Google Drive:</span>
                    <span className="text-[11px] text-slate-600 block leading-relaxed">
                      ท่านสามารถกดปุ่ม <strong>"เปิดดูใน Google Drive"</strong> ด้านล่าง แล้วลากไฟล์ข้อสอบไปวางในโฟลเดอร์ของอาจารย์ได้โดยตรง
                    </span>
                  </div>
                )}
              </div>

              <div className="flex flex-col sm:flex-row items-center justify-center gap-2 pt-1">
                {uploadSuccessResult.fileUrl && (
                  <a
                    href={uploadSuccessResult.fileUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-full sm:w-auto px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-semibold shadow-2xs transition inline-flex items-center justify-center gap-1.5"
                  >
                    <ExternalLink className="w-3.5 h-3.5" />
                    <span>เปิดดูใน Google Drive</span>
                  </a>
                )}
                <button
                  type="button"
                  onClick={onClose}
                  className="w-full sm:w-auto px-5 py-2 bg-white text-slate-700 hover:bg-slate-100 border border-slate-300 rounded-xl text-xs font-semibold transition cursor-pointer"
                >
                  เสร็จสิ้น / ปิดหน้าต่าง
                </button>
              </div>
            </div>
          ) : isLocked ? (
            <div className="p-5 bg-amber-50/80 border-2 border-amber-300 rounded-2xl text-center space-y-3.5 animate-in zoom-in-95 duration-200">
              <div className="w-12 h-12 rounded-full bg-amber-100 text-amber-700 flex items-center justify-center mx-auto border border-amber-200 shadow-2xs">
                <Lock className="w-6 h-6 text-amber-600" />
              </div>
              <div>
                <h4 className="font-bold text-base text-amber-950">
                  รายวิชานี้ส่งข้อสอบเรียบร้อยแล้ว (พร้อมสอบ ✔)
                </h4>
                <p className="text-xs text-amber-900 mt-1 leading-relaxed">
                  ระบบได้ตั้งเงื่อนไข <strong className="text-amber-950">ห้ามอัปโหลดหรือส่งข้อสอบซ้ำ</strong> เพื่อป้องกันการส่งข้อสอบซ้ำซ้อน
                </p>
                {exam.examSubmissionDate && (
                  <p className="text-[11px] text-amber-800 mt-1.5 font-mono font-semibold bg-white/80 py-1 px-3 rounded-lg inline-block border border-amber-200">
                    บันทึกสถานะเมื่อ: {exam.examSubmissionDate}
                  </p>
                )}
              </div>

              <div className="p-3 bg-white/90 rounded-xl border border-amber-200 text-left text-xs text-slate-700 space-y-1">
                <span className="font-bold text-slate-800 flex items-center gap-1">
                  <AlertCircle className="w-3.5 h-3.5 text-amber-600 shrink-0" />
                  <span>คำแนะนำ:</span>
                </span>
                <span className="text-[11px] text-slate-600 block leading-relaxed">
                  หากท่านต้องการตรวจดูไฟล์ใน Google Drive สามารถกดปุ่มด้านล่างได้ทันที แต่หากมีความจำเป็นต้องเปลี่ยนไฟล์ต้นฉบับข้อสอบ กรุณาติดต่อผู้ดูแลระบบ (Admin) เพื่อทำการปลดล็อก
                </span>
              </div>

              <div className="flex flex-col sm:flex-row items-center justify-center gap-2 pt-2 border-t border-amber-200/60">
                <a
                  href={exam.examLink || exam.driveFolderUrl || centralDriveFolderUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full sm:w-auto px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-semibold shadow-2xs transition inline-flex items-center justify-center gap-1.5"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>เปิดดูใน Google Drive</span>
                </a>
                <button
                  type="button"
                  onClick={onClose}
                  className="w-full sm:w-auto px-5 py-2 bg-white text-slate-700 hover:bg-slate-100 border border-slate-300 rounded-xl text-xs font-semibold transition cursor-pointer"
                >
                  ปิดหน้าต่าง
                </button>
              </div>
            </div>
          ) : (
            <>
              {/* File Upload Selector */}
              <div className="space-y-2">
                <label className="block text-xs font-bold text-slate-800">
                  1. เลือกไฟล์ต้นฉบับข้อสอบ (PDF, Word .docx, .doc):
                </label>
                <div className="border-2 border-dashed border-emerald-300 hover:border-emerald-500 bg-emerald-50/30 rounded-2xl p-4 text-center cursor-pointer relative transition">
                  <input
                    type="file"
                    accept=".pdf,.doc,.docx"
                    onChange={handleFileChange}
                    className="absolute inset-0 opacity-0 cursor-pointer"
                  />
                  <div className="space-y-1.5 pointer-events-none">
                    <Upload className="w-8 h-8 text-emerald-600 mx-auto" />
                    {selectedFile ? (
                      <div className="bg-white p-2 rounded-xl border border-emerald-300 inline-block max-w-full">
                        <p className="font-bold text-xs text-emerald-950 truncate">
                          📄 {selectedFile.name}
                        </p>
                        <p className="text-[11px] text-emerald-700">
                          ขนาด {(selectedFile.size / (1024 * 1024)).toFixed(2)} MB · คลิกเพื่อเปลี่ยนไฟล์
                        </p>
                      </div>
                    ) : (
                      <div>
                        <p className="font-bold text-xs text-slate-700">
                          คลิกหรือลากไฟล์ข้อสอบมาวางที่นี่
                        </p>
                        <p className="text-[11px] text-slate-400">
                          รองรับไฟล์ PDF, Word (.docx, .doc) ขนาดไม่เกิน 25 MB
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Optional Drive link input */}
              <div className="space-y-1.5">
                <label className="block text-xs font-semibold text-slate-700 flex items-center gap-1">
                  <LinkIcon className="w-3.5 h-3.5 text-emerald-600" />
                  <span>2. ลิงก์ไฟล์หรือโฟลเดอร์ Google Drive (ทางเลือกเพิ่มเติม):</span>
                </label>
                <input
                  type="url"
                  value={customDriveLink}
                  onChange={(e) => setCustomDriveLink(e.target.value)}
                  placeholder="https://drive.google.com/..."
                  className="w-full px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 text-slate-800"
                />
                <p className="text-[10px] text-slate-500">
                  หากนำไฟล์ไปวางใน Google Drive แล้ว สามารถนำลิงก์มาวางที่นี่ได้
                </p>
              </div>

              {/* Progress & Error Notification */}
              {isUploading && (
                <div className="p-3 bg-emerald-50 rounded-xl border border-emerald-200 text-xs text-emerald-900 flex items-center gap-2">
                  <div className="w-4 h-4 border-2 border-emerald-600 border-t-transparent rounded-full animate-spin"></div>
                  <span>{uploadProgress || 'กำลังประมวลผลการส่งข้อสอบ...'}</span>
                </div>
              )}

              {errorMessage && (
                <div className="p-3 bg-rose-50 rounded-xl border border-rose-200 text-xs text-rose-800 flex items-start gap-2">
                  <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
                  <span>{errorMessage}</span>
                </div>
              )}

              {/* Notice for Webhook vs Manual Drive */}
              {!webhookUrl && (
                <div className="p-3 bg-emerald-50/70 rounded-2xl border border-emerald-200 text-xs text-emerald-950 space-y-1">
                  <div className="flex items-center gap-1.5 font-bold text-emerald-950">
                    <Sparkles className="w-4 h-4 text-emerald-700 shrink-0" />
                    <span>คำแนะนำการส่งข้อสอบ:</span>
                  </div>
                  <p className="text-[11px] text-emerald-850 leading-relaxed">
                    เมื่อกดปุ่มด้านล่าง ระบบจะ <strong>บันทึกสถานะรายวิชานี้เป็น "พร้อมสอบ ✔"</strong> ทันที
                  </p>
                  <p className="text-[11px] text-emerald-950 font-semibold pt-0.5">
                    👉 ท่านสามารถกดปุ่ม <strong>"เปิด Google Drive กลาง"</strong> ด้านล่าง เพื่อลากไฟล์ PDF/Word ไปวางในโฟลเดอร์ของอาจารย์ได้โดยตรง
                  </p>
                </div>
              )}

              {/* Action Buttons Section (Always visible and prominent!) */}
              <div className="space-y-2.5 pt-3 border-t border-slate-100">
                {/* PRIMARY SUBMIT BUTTON */}
                <button
                  type="button"
                  disabled={isUploading}
                  onClick={handlePrimarySubmit}
                  className="w-full py-3 px-4 bg-emerald-600 hover:bg-emerald-700 active:scale-[0.99] disabled:opacity-50 text-white font-bold text-sm rounded-xl shadow-md hover:shadow-lg transition flex items-center justify-center gap-2 cursor-pointer"
                >
                  <Send className="w-4 h-4" />
                  <span>
                    {webhookUrl && selectedFile
                      ? 'อัปโหลดและบันทึกสถานะ "พร้อมสอบ ✔" ทันที'
                      : selectedFile
                      ? 'ยืนยันการส่งข้อสอบ (ปรับสถานะเป็น "พร้อมสอบ ✔")'
                      : 'ยืนยันส่งข้อสอบ (ปรับสถานะเป็น "พร้อมสอบ ✔")'}
                  </span>
                </button>

                {/* Secondary Drive Folder Button */}
                <a
                  href={centralDriveFolderUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full py-2.5 px-3 bg-white hover:bg-emerald-50 text-emerald-900 border border-emerald-300 font-semibold text-xs rounded-xl transition flex items-center justify-center gap-1.5 shadow-2xs"
                >
                  <Folder className="w-4 h-4 text-emerald-700" />
                  <span>เปิด Google Drive กลาง เพื่อสร้างโฟลเดอร์/วางไฟล์ด้วยตนเอง</span>
                  <ExternalLink className="w-3.5 h-3.5 opacity-70" />
                </a>

                {/* Cancel Button */}
                <button
                  type="button"
                  onClick={onClose}
                  className="w-full py-2 text-center text-xs text-slate-500 hover:text-slate-800 font-medium transition cursor-pointer"
                >
                  ยกเลิก
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};
export default ExamUploadDriveModal;
